sudo: required
services:
  - docker

before_install:
  - docker build -t vivekdodeja/reactapp -f Dockerfile.dev .

script:
  - docker run -e CI=true vivekdodeja/reactapp npm run test -- --coverage

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "reactapp"
  env: "Reactapp-env"
  bucket_name: "elasticbeanstalk-us-west-2-550923637492"
  bucket_path: "reactapp"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
  on:
    branch: master